import { Router } from 'express';

import authRoutes from './auth.routes';
import adminAuthRoutes from './adminAuth.routes';
import categoryRoutes from './category.routes';
import brandRoutes from './brand.routes';
import productRoutes from './product.routes';
import cartRoutes from './cart.routes';
import compareRoutes from './compare.routes';
import wishlistRoutes from './wishlist.routes';
import addressRoutes from './address.routes';
import checkoutRoutes from './checkout.routes';
import paymentRoutes from './payment.routes';
import orderRoutes from './order.routes';
import reviewRoutes from './review.routes';
import expertReviewRoutes from './expertReview.routes';
import blogRoutes from './blog.routes';
import blogCategoryRoutes from './blogCategory.routes';
import bannerRoutes from './banner.routes';
import homepageSectionRoutes from './homepageSection.routes';
import couponRoutes from './coupon.routes';
import offerRoutes from './offer.routes';
import leadRoutes from './lead.routes';
import contactRoutes from './contact.routes';
import faqRoutes from './faq.routes';
import pageRoutes from './page.routes';
import settingsRoutes from './settings.routes';
import uploadRoutes from './upload.routes';
import inventoryRoutes from './inventory.routes';
import adminDashboardRoutes from './adminDashboard.routes';
import roleRoutes from './role.routes';
import adminManagementRoutes from './adminManagement.routes';
import activityLogRoutes from './activityLog.routes';
import notificationRoutes from './notification.routes';
import userRoutes from './user.routes';
import abandonedCartRoutes from './abandonedCart.routes';
import taxRoutes from './tax.routes';
import exportRoutes from './export.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/categories', categoryRoutes);
router.use('/brands', brandRoutes);
router.use('/products', productRoutes);
router.use('/cart', cartRoutes);
router.use('/compare', compareRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/addresses', addressRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/payments', paymentRoutes);
router.use('/orders', orderRoutes);
router.use('/reviews', reviewRoutes);
router.use('/expert-reviews', expertReviewRoutes);
router.use('/blogs', blogRoutes);
router.use('/blog-categories', blogCategoryRoutes);
router.use('/banners', bannerRoutes);
router.use('/homepage-sections', homepageSectionRoutes);
router.use('/coupons', couponRoutes);
router.use('/offers', offerRoutes);
router.use('/leads', leadRoutes);
router.use('/contact', contactRoutes);
router.use('/faqs', faqRoutes);
router.use('/pages', pageRoutes);
router.use('/settings', settingsRoutes);
router.use('/uploads', uploadRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin/roles', roleRoutes);
router.use('/admin/admins', adminManagementRoutes);
router.use('/admin/activity-log', activityLogRoutes);
router.use('/notifications', notificationRoutes);
router.use('/users', userRoutes);
router.use('/abandoned-carts', abandonedCartRoutes);
router.use('/taxes', taxRoutes);
router.use('/exports', exportRoutes);

export default router;
